<?php
function greeting_menu() {
    $items = array();
    $items['hello_there'] = array(
        'title' => "Hello there!",
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['goodbye'] = array(
        'title' => "Goodbye",
        'page callback' => 'say_goodbye',
        'access callback'=> TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function say_hello() {
    return '<p>Hello there friend!</p>';
}

function say_goodbye(){
    return '<p>Goodbye my friend!</p>';
}

function greeting_user_login(){
    $_GET['destination'] = 'hello_there';
}

function greeting_user_logout(){
    $_GET['destination'] = 'goodbye';
}
